/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.djt;

import org.junit.Test;
import static org.junit.Assert.*;

public class FreedomLivingAcresAppTest {
    @Test public void testAppHasAGreeting() {
        FreedomLivingAcresApp classUnderTest = new FreedomLivingAcresApp();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
